//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIObservabilitySummarizer) DeepCopyInto(out *AIObservabilitySummarizer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIObservabilitySummarizer.
func (in *AIObservabilitySummarizer) DeepCopy() *AIObservabilitySummarizer {
	if in == nil {
		return nil
	}
	out := new(AIObservabilitySummarizer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIObservabilitySummarizer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIObservabilitySummarizerList) DeepCopyInto(out *AIObservabilitySummarizerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AIObservabilitySummarizer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIObservabilitySummarizerList.
func (in *AIObservabilitySummarizerList) DeepCopy() *AIObservabilitySummarizerList {
	if in == nil {
		return nil
	}
	out := new(AIObservabilitySummarizerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AIObservabilitySummarizerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIObservabilitySummarizerSpec) DeepCopyInto(out *AIObservabilitySummarizerSpec) {
	*out = *in
	if in.RAG != nil {
		in, out := &in.RAG, &out.RAG
		*out = new(RAGConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RAGBackendRef != nil {
		in, out := &in.RAGBackendRef, &out.RAGBackendRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.MCPServer != nil {
		in, out := &in.MCPServer, &out.MCPServer
		*out = new(MCPServerConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.MCPServerRef != nil {
		in, out := &in.MCPServerRef, &out.MCPServerRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ConsolePlugin != nil {
		in, out := &in.ConsolePlugin, &out.ConsolePlugin
		*out = new(ConsolePluginConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ConsolePluginRef != nil {
		in, out := &in.ConsolePluginRef, &out.ConsolePluginRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
	if in.ObservabilityStack != nil {
		in, out := &in.ObservabilityStack, &out.ObservabilityStack
		*out = new(ObservabilityStackConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.ObservabilityStackRef != nil {
		in, out := &in.ObservabilityStackRef, &out.ObservabilityStackRef
		*out = new(v1.LocalObjectReference)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIObservabilitySummarizerSpec.
func (in *AIObservabilitySummarizerSpec) DeepCopy() *AIObservabilitySummarizerSpec {
	if in == nil {
		return nil
	}
	out := new(AIObservabilitySummarizerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AIObservabilitySummarizerStatus) DeepCopyInto(out *AIObservabilitySummarizerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Components.DeepCopyInto(&out.Components)
	if in.InstalledOperators != nil {
		in, out := &in.InstalledOperators, &out.InstalledOperators
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Health.DeepCopyInto(&out.Health)
	if in.LastReconcileTime != nil {
		in, out := &in.LastReconcileTime, &out.LastReconcileTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AIObservabilitySummarizerStatus.
func (in *AIObservabilitySummarizerStatus) DeepCopy() *AIObservabilitySummarizerStatus {
	if in == nil {
		return nil
	}
	out := new(AIObservabilitySummarizerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentHealth) DeepCopyInto(out *ComponentHealth) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentHealth.
func (in *ComponentHealth) DeepCopy() *ComponentHealth {
	if in == nil {
		return nil
	}
	out := new(ComponentHealth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
	if in.LastUpdateTime != nil {
		in, out := &in.LastUpdateTime, &out.LastUpdateTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentsStatus) DeepCopyInto(out *ComponentsStatus) {
	*out = *in
	in.RAG.DeepCopyInto(&out.RAG)
	in.MCPServer.DeepCopyInto(&out.MCPServer)
	in.ConsolePlugin.DeepCopyInto(&out.ConsolePlugin)
	in.UI.DeepCopyInto(&out.UI)
	in.MinIO.DeepCopyInto(&out.MinIO)
	in.Tempo.DeepCopyInto(&out.Tempo)
	in.Loki.DeepCopyInto(&out.Loki)
	in.OTelCollector.DeepCopyInto(&out.OTelCollector)
	in.Korrel8r.DeepCopyInto(&out.Korrel8r)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentsStatus.
func (in *ComponentsStatus) DeepCopy() *ComponentsStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsolePluginConfig) DeepCopyInto(out *ConsolePluginConfig) {
	*out = *in
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsolePluginConfig.
func (in *ConsolePluginConfig) DeepCopy() *ConsolePluginConfig {
	if in == nil {
		return nil
	}
	out := new(ConsolePluginConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthStatus) DeepCopyInto(out *HealthStatus) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = make(map[string]ComponentHealth, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.LastCheckTime != nil {
		in, out := &in.LastCheckTime, &out.LastCheckTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthStatus.
func (in *HealthStatus) DeepCopy() *HealthStatus {
	if in == nil {
		return nil
	}
	out := new(HealthStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LokiConfig) DeepCopyInto(out *LokiConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LokiConfig.
func (in *LokiConfig) DeepCopy() *LokiConfig {
	if in == nil {
		return nil
	}
	out := new(LokiConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MCPServerConfig) DeepCopyInto(out *MCPServerConfig) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MCPServerConfig.
func (in *MCPServerConfig) DeepCopy() *MCPServerConfig {
	if in == nil {
		return nil
	}
	out := new(MCPServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MinIOConfig) DeepCopyInto(out *MinIOConfig) {
	*out = *in
	if in.Buckets != nil {
		in, out := &in.Buckets, &out.Buckets
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MinIOConfig.
func (in *MinIOConfig) DeepCopy() *MinIOConfig {
	if in == nil {
		return nil
	}
	out := new(MinIOConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OTelCollectorConfig) DeepCopyInto(out *OTelCollectorConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OTelCollectorConfig.
func (in *OTelCollectorConfig) DeepCopy() *OTelCollectorConfig {
	if in == nil {
		return nil
	}
	out := new(OTelCollectorConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityMinIOConfig) DeepCopyInto(out *ObservabilityMinIOConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityMinIOConfig.
func (in *ObservabilityMinIOConfig) DeepCopy() *ObservabilityMinIOConfig {
	if in == nil {
		return nil
	}
	out := new(ObservabilityMinIOConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ObservabilityStackConfig) DeepCopyInto(out *ObservabilityStackConfig) {
	*out = *in
	if in.MinIO != nil {
		in, out := &in.MinIO, &out.MinIO
		*out = new(ObservabilityMinIOConfig)
		**out = **in
	}
	if in.Tempo != nil {
		in, out := &in.Tempo, &out.Tempo
		*out = new(TempoConfig)
		**out = **in
	}
	if in.Loki != nil {
		in, out := &in.Loki, &out.Loki
		*out = new(LokiConfig)
		**out = **in
	}
	if in.OTelCollector != nil {
		in, out := &in.OTelCollector, &out.OTelCollector
		*out = new(OTelCollectorConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ObservabilityStackConfig.
func (in *ObservabilityStackConfig) DeepCopy() *ObservabilityStackConfig {
	if in == nil {
		return nil
	}
	out := new(ObservabilityStackConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PostgreSQLConfig) DeepCopyInto(out *PostgreSQLConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PostgreSQLConfig.
func (in *PostgreSQLConfig) DeepCopy() *PostgreSQLConfig {
	if in == nil {
		return nil
	}
	out := new(PostgreSQLConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RAGConfig) DeepCopyInto(out *RAGConfig) {
	*out = *in
	if in.PostgreSQL != nil {
		in, out := &in.PostgreSQL, &out.PostgreSQL
		*out = new(PostgreSQLConfig)
		**out = **in
	}
	if in.MinIO != nil {
		in, out := &in.MinIO, &out.MinIO
		*out = new(MinIOConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.GPUTolerations != nil {
		in, out := &in.GPUTolerations, &out.GPUTolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RAGConfig.
func (in *RAGConfig) DeepCopy() *RAGConfig {
	if in == nil {
		return nil
	}
	out := new(RAGConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TempoConfig) DeepCopyInto(out *TempoConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TempoConfig.
func (in *TempoConfig) DeepCopy() *TempoConfig {
	if in == nil {
		return nil
	}
	out := new(TempoConfig)
	in.DeepCopyInto(out)
	return out
}
